"""PDF compliance report generator using fpdf2."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from fpdf import FPDF

from agentaudit_api.models.event import AuditEvent


def generate_pdf(
    *,
    stats: dict[str, Any],
    risky_events: list[AuditEvent],
    framework_counts: dict[str, dict[str, int]],
    after: datetime | None,
    before: datetime | None,
    time_range: str,
) -> bytes:
    """Generate a compliance report PDF and return raw bytes.

    Args:
        stats: Aggregate statistics from get_stats.
        risky_events: List of high/critical risk events to include.
        framework_counts: Framework article counts.
        after: Start of the report period.
        before: End of the report period.
        time_range: Human-readable time range label.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "AgenticAudit Compliance Report", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Period
    pdf.set_font("Helvetica", "", 11)
    if after and before:
        period = f"{after.strftime('%Y-%m-%d %H:%M')} - {before.strftime('%Y-%m-%d %H:%M')} UTC"
    elif time_range:
        period = f"Last {time_range}"
    else:
        period = "All time"
    pdf.cell(0, 7, f"Period: {period}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Summary
    _section_header(pdf, "Summary")
    _kv(pdf, "Total Events", str(stats.get("total_events", 0)))
    _kv(pdf, "PII Events", str(stats.get("pii_events", 0)))
    _kv(pdf, "Unique Agents", str(stats.get("unique_agents", 0)))
    _kv(pdf, "Unique Sessions", str(stats.get("unique_sessions", 0)))
    pdf.ln(2)

    by_risk: dict[str, int] = stats.get("by_risk_level", {})
    for level in ("low", "medium", "high", "critical"):
        _kv(pdf, f"  {level.capitalize()}", str(by_risk.get(level, 0)))
    pdf.ln(6)

    # Framework coverage
    _section_header(pdf, "Framework Coverage")
    if framework_counts:
        for fw_name, articles in sorted(framework_counts.items()):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, fw_name.upper(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for art, count in sorted(articles.items()):
                label = f"{fw_name.upper()} {art.replace('_', ' ').title()}"
                pdf.cell(0, 5, f"  {label}: {count} events", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, "No framework mappings found in this period.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Top high/critical events
    _section_header(pdf, "Top High/Critical Risk Events")
    if risky_events:
        for i, ev in enumerate(risky_events, 1):
            pdf.set_font("Helvetica", "B", 9)
            created = ev.created_at.strftime("%Y-%m-%d %H:%M:%S") if ev.created_at else "?"
            risk = ev.risk_level or "unknown"
            pdf.cell(
                0,
                5,
                f"{i}. [{risk.upper()}] {ev.action} - {ev.agent_id} ({created})",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.set_font("Helvetica", "", 8)
            data_str = str(ev.data or {})
            if len(data_str) > 120:
                data_str = data_str[:120] + "..."
            pdf.cell(0, 4, f"   Data: {data_str}", new_x="LMARGIN", new_y="NEXT")
            if ev.pii_detected:
                pdf.cell(
                    0,
                    4,
                    f"   PII: {', '.join(ev.pii_fields) if ev.pii_fields else 'detected'}",
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
            pdf.ln(1)
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, "No high/critical events in this period.", new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    pdf.cell(0, 5, f"Generated by AgenticAudit | {timestamp}", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def _section_header(pdf: FPDF, title: str) -> None:
    """Render a section header with an underline."""
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(100, 100, 100)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)


def _kv(pdf: FPDF, key: str, value: str) -> None:
    """Render a key-value row in the PDF."""
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 6, key, new_x="RIGHT")
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")
